baseurl = "/"
languageCode = "ko-kr"
theme = "hello-friend-ng"
favicon = "favicon.ico"
enableEmoji = true
[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "조은우 개발자 블로그"
  keywords = "blog, development, programming, tech, python, javascript, golang, go, postgresql, devops, elasticsearch, fluend, kubernetes, docker"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "light"

[languages]
  [languages.en]
    title = "조은우 개발 블로그"
    subtitle = ""
    keywords = "blog, development, programming, tech, python, javascript, golang, go, postgresql, devops, elasticsearch, fluend, kubernetes, docker"
    copyright = "Jonnung"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "조은우 개발 블로그"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

	# You can create a language based menu
    [languages.en.menu]
#      [[languages.en.menu.main]]
#        identifier = "about"
#        name = "About"
#        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Posts"
        url = "/posts"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
